name: flow_eval
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - adwaita-icon-theme=49.0=unix_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=mkl
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.11.11=py311hd8ed1ab_1
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.12=py311hfdbb021_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - epoxy=1.5.10=h166bdaf_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ffmpeg=8.0.1=gpl_h35c3513_706
  - filelock=3.16.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=hd590300_0
  - glib-tools=2.86.3=hf516916_0
  - glslang=16.1.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311h0f6cedb_3
  - gnutls=3.7.6=he274497_3
  - graphite2=1.3.14=hecca717_2
  - gtk3=3.24.43=h021d004_4
  - gts=0.7.6=h977cf35_4
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=12.3.0=h6083320_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.27.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.9.0=20_linux64_mkl
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=20_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.7.77=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libfabric=2.0.0=ha770c72_1
  - libfabric1=2.0.0=h14e6f36_1
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgd=2.3.3=h5fbf134_12
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=20_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hd590300_0
  - libpmix=6.0.0=h9b03745_2
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.47.2=hee588c1_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=258.2=h07e904d_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h07e904d_0
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.11.9=pyhd8ed1ab_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpi=1.0=openmpi
  - mpi4py=4.0.1=py311ha982e2a_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.23.4.1=h2b5d15b_3
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.8.1=hc379101_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openmpi=5.0.8=external_hcc19f6a_9
  - openssl=3.6.0=h26f9b46_0
  - p11-kit=0.25.3=he72ba39_0
  - packaging=24.2=pyhd8ed1ab_2
  - pango=1.56.4=hadf4263_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.11=5_cp311
  - pytorch=2.4.0=py3.11_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=26.2.0=py311h7deb3e3_3
  - rdma-core=55.0=h5888daf_0
  - readline=8.2=h8228510_1
  - requests=2.32.5=pyhcf101f3_1
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.22=h68140b3_0
  - setuptools=75.6.0=pyhff2d567_1
  - shaderc=2025.5=h3e344bc_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hecca717_0
  - tbb=2021.13.0=hb700be7_5
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.0=py311_cu124
  - torchtriton=3.0.0=py311
  - torchvision=0.19.0=py311_cu124
  - tornado=6.4.2=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucc=1.3.0=h0f835a6_3
  - ucx=1.17.0=h1b0e7dc_4
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antspyx==0.6.1
      - attrs==25.3.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - certifi==2025.11.12
      - chart-studio==1.1.0
      - click==8.3.0
      - coloredlogs==15.0.1
      - comet-ml==3.52.1
      - configobj==5.0.9
      - connected-components-3d==3.26.1
      - contourpy==1.3.3
      - ctfm==0.1.0
      - cycler==0.12.1
      - deprecated==1.2.18
      - diffusers==0.35.2
      - dulwich==0.24.1
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - everett==3.1.0
      - fastremap==1.17.7
      - fill-voids==2.1.1
      - flatbuffers==25.12.19
      - fonttools==4.61.0
      - formulaic==1.2.0
      - frozenlist==1.8.0
      - gdcm==1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - humanize==4.13.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - ipywidgets==8.1.8
      - itk==5.4.5
      - itk-core==5.4.5
      - itk-filtering==5.4.5
      - itk-io==5.4.5
      - itk-numerics==5.4.5
      - itk-registration==5.4.5
      - itk-segmentation==5.4.5
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lifelines==0.30.0
      - lightning==2.6.0
      - lungmask==0.2.20
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - monai==1.5.1
      - monai-generative==0.2.3
      - more-itertools==10.8.0
      - multidict==6.7.0
      - narwhals==2.13.0
      - networkx==3.6
      - nibabel==5.3.2
      - numpy==2.2.6
      - onnx==1.20.1
      - onnxruntime==1.23.2
      - onnxsim==0.4.36
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pandas==2.3.3
      - pastel==0.2.1
      - patsy==1.0.2
      - pillow==12.0.0
      - plotly==6.5.0
      - poethepoet==0.10.0
      - pot==0.9.6.post1
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==21.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydicom==3.0.1
      - pylibjpeg==2.1.0
      - pylibjpeg-libjpeg==2.3.0
      - pylibjpeg-openjpeg==2.5.0
      - pyparsing==3.2.5
      - python-box==6.1.0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rich==14.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentry-sdk==2.38.0
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - simplejson==3.20.1
      - simsimd==6.5.3
      - smmap==5.0.2
      - statsmodels==0.14.5
      - stringzilla==4.0.13
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.24
      - tomlkit==0.13.3
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchinfo==1.8.0
      - torchio==0.20.22
      - torchmetrics==1.8.2
      - torchsde==0.2.6
      - torchview==0.2.7
      - trampoline==0.1.2
      - typer==0.18.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - vae3d2d==0.2.0
      - wandb==0.23.0
      - webcolors==25.10.0
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - wurlitzer==3.1.1
      - yarl==1.22.0
prefix: /data/rbg/users/duitz/miniforge3/envs/flow_eval
