name: flow_eval
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adwaita-icon-theme=49.0
  - alsa-lib=1.2.15.3
  - aom=3.9.1
  - asttokens=3.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attr=2.5.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.11
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.12
  - decorator=5.1.1
  - epoxy=1.5.10
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=8.0.1
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2024.12.0
  - gdk-pixbuf=2.44.4
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib-tools=2.86.3
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.6
  - graphite2=1.3.14
  - gtk3=3.24.43
  - gts=0.7.6
  - h2=4.1.0
  - harfbuzz=12.3.0
  - hicolor-icon-theme=0.17
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.5.0
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.31.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.27.0
  - libabseil=20250512.1
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.4
  - libblas=3.9.0
  - libcap=2.76
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.3
  - libfabric=2.0.0
  - libfabric1=2.0.0
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.12.2
  - libiconv=1.18
  - libidn2=2.3.7
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpmix=6.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=258.2
  - libtasn1=4.19.0
  - libtiff=4.7.1
  - libudev1=258.2
  - libunistring=0.9.10
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lightning-utilities=0.11.9
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpi=1.0
  - mpi4py=4.0.1
  - mpmath=1.3.0
  - nccl=2.23.4.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.8.1
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openmpi=5.0.8
  - openssl=3.6.0
  - p11-kit=0.25.3
  - packaging=24.2
  - pango=1.56.4
  - parso=0.8.4
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - pixman=0.46.4
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - pyzmq=26.2.0
  - rdma-core=55.0
  - readline=8.2
  - requests=2.32.5
  - sdl2=2.32.56
  - sdl3=3.2.22
  - setuptools=75.6.0
  - shaderc=2025.5
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.15.0
  - ucc=1.3.0
  - ucx=1.17.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antspyx==0.6.1
      - attrs==25.3.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - certifi==2025.11.12
      - chart-studio==1.1.0
      - click==8.3.0
      - coloredlogs==15.0.1
      - comet-ml==3.52.1
      - configobj==5.0.9
      - connected-components-3d==3.26.1
      - contourpy==1.3.3
      - ctfm==0.1.0
      - cycler==0.12.1
      - deprecated==1.2.18
      - diffusers==0.35.2
      - dulwich==0.24.1
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - everett==3.1.0
      - fastremap==1.17.7
      - fill-voids==2.1.1
      - flatbuffers==25.12.19
      - fonttools==4.61.0
      - formulaic==1.2.0
      - frozenlist==1.8.0
      - gdcm==1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - humanize==4.13.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - ipywidgets==8.1.8
      - itk==5.4.5
      - itk-core==5.4.5
      - itk-filtering==5.4.5
      - itk-io==5.4.5
      - itk-numerics==5.4.5
      - itk-registration==5.4.5
      - itk-segmentation==5.4.5
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lifelines==0.30.0
      - lightning==2.6.0
      - lungmask==0.2.20
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - monai==1.5.1
      - monai-generative==0.2.3
      - more-itertools==10.8.0
      - multidict==6.7.0
      - narwhals==2.13.0
      - networkx==3.6
      - nibabel==5.3.2
      - numpy==2.2.6
      - onnx==1.20.1
      - onnxruntime==1.23.2
      - onnxsim==0.4.36
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pandas==2.3.3
      - pastel==0.2.1
      - patsy==1.0.2
      - pillow==12.0.0
      - plotly==6.5.0
      - poethepoet==0.10.0
      - pot==0.9.6.post1
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==21.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydicom==3.0.1
      - pylibjpeg==2.1.0
      - pylibjpeg-libjpeg==2.3.0
      - pylibjpeg-openjpeg==2.5.0
      - pyparsing==3.2.5
      - python-box==6.1.0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rich==14.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentry-sdk==2.38.0
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - simplejson==3.20.1
      - simsimd==6.5.3
      - smmap==5.0.2
      - statsmodels==0.14.5
      - stringzilla==4.0.13
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.24
      - tomlkit==0.13.3
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchinfo==1.8.0
      - torchio==0.20.22
      - torchmetrics==1.8.2
      - torchsde==0.2.6
      - torchview==0.2.7
      - trampoline==0.1.2
      - typer==0.18.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - vae3d2d==0.2.0
      - wandb==0.23.0
      - webcolors==25.10.0
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - wurlitzer==3.1.1
      - yarl==1.22.0
prefix: /data/rbg/users/duitz/miniforge3/envs/flow_eval
