wandb_project: paired_model_3d_fm_rand
wandb_run_name: all_image_raw
experiment_name: all_image_raw
debug_flag: false
train_batch_size: 1
test_batch_size: 1
lr: 0.0005
img_size:  [32, 128, 128] # [16, 16, 16]
num_samples: null
num_devices: 3