wandb_project: pretrained_3d_models
wandb_run_name: final_full_latent
experiment_name: final_full_latent
debug_flag: false
train_batch_size: 16
test_batch_size: 8
lr: 0.0005
img_size: [16, 16, 16] # [32, 128, 128]
num_samples: null
