# configs/paths.yaml

nifti_dir: /data/rbg/scratch/lung_ct/nlst_nifti
nifti_transformed_dir: /data/rbg/scratch/lung_ct/nlst_nifti_transformed
parquet_dir: /data/rbg/users/duitz/CT-generative-pred/metadata
registration_dir: /data/rbg/scratch/lung_ct/registration_zack

metadata_dir: /data/rbg/users/duitz/CT-generative-pred/metadata

# Root for the shared NLST JSON / PNG / annotations
shared_nlst_root: /data/rbg/shared/datasets/NLST/NLST # This one was checked

# After creating parquets file paths Train
full_data_train_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/train/full_data_single_timepoints.parquet
full_data_train_paired_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/train/full_data_paired_exams.parquet
full_data_train_timelines_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/train/full_data_timelines.parquet

# After creating parquets file paths Val
full_data_val_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/dev/full_data_single_timepoints.parquet
full_data_val_paired_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/dev/full_data_paired_exams.parquet
full_data_val_timelines_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/dev/full_data_timelines.parquet

# After creating parquets file paths Test
full_data_test_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/test/full_data_single_timepoints.parquet
full_data_test_paired_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/test/full_data_paired_exams.parquet
full_data_test_timelines_parquet: /data/rbg/users/duitz/CT-generative-pred/metadata/test/full_data_timelines.parquet

