# ---- model hyperparameters (UNet) ----
spatial_dims: 3
in_channels: 16
out_channels: 16
channels: [64, 128, 256]
num_res_blocks: [2, 3, 3]
resblock_updown: true
attention_levels: [false, true, true]
num_head_channels: 16
norm_num_groups: 8


