# configs/vae_3d_model.yaml

# Names
model_name: single_zero_beta.pt

# --- Attention configs ---
attn_params:
  num_heads: 4
  dim_head: 32
  dropout: 0.1
  window_size: [4, 8, 8] # null for global attention
  use_rel_pos_bias: true

use_attn: false

# --- Activation ---
# Options for Gelu are { approximate: none | tanh | erf }
act:
  - GELU
  - { approximate: none }

# --- CustomVAE core params ---
vae_latent_channels: 16 # was 128
debug_mode: false
upsample_mode: deconv
init_filters: 64
smallest_filters: 64 # was 128
beta: 0
vae_use_log_var: true
use_checkpoint: true

blocks_down:  [1, 1, 2] #[1, 2, 4]
blocks_up: [1, 1] # [1, 1]
downsample_strides: [[1,2,2], [2,2,2]] # Strides start after the first block down 
vae_down_stride: [1,2,2]

# Other configs
num_groups: 8
in_channels: 1
dropout_prob: null
